
// Dictionary for FullPlayerData fields
const FullPlayerDataFieldInfo = {
    playerId: {
      label: "Player ID",
      description: "Unique identifier for the player.",
      checked: false,
      type: "number",
      reverse: false,
      fields: {}
    },
    playerBio: {
      label: "Player Bio",
      description: "Biographical information about the player.",
      checked: true,
      reverse: false,
      fields: {
        name: { label: "Name", description: "Full name of the player.", checked: true, type: "string", reverse: false },
        firstName: { label: "First Name", description: "Player's first name.", checked: false, type: "string", reverse: false },
        lastName: { label: "Last Name", description: "Player's last name.", checked: false, type: "string", reverse: false },
        birthDate: { label: "Birth Date", description: "Player's date of birth (ISO format).", checked: true, type: "string", reverse: true },
        height: { label: "Height", description: "Player's height in inches.", checked: true, type: "number", reverse: false },
        weight: { label: "Weight", description: "Player's weight in pounds.", checked: true, type: "number", reverse: false },
        highSchool: { label: "High School", description: "Name of the high school attended by the player.", checked: false, type: "string", reverse: false },
        highSchoolState: { label: "High School State", description: "State of the high school attended.", checked: false, type: "string", reverse: false },
        homeTown: { label: "Hometown", description: "Player's hometown.", checked: false, type: "string", reverse: false },
        homeState: { label: "Home State", description: "Player's home state.", checked: false, type: "string", reverse: false },
        homeCountry: { label: "Home Country", description: "Player's home country.", checked: false, type: "string", reverse: false },
        nationality: { label: "Nationality", description: "Player's nationality.", checked: false, type: "string", reverse: false },
        photoUrl: { label: "Photo URL", description: "URL to the player's photo.", checked: false, type: "string", reverse: false },
        currentTeam: { label: "Current Team", description: "Player's current team.", checked: true, type: "string", reverse: false },
        league: { label: "League", description: "League in which the player is currently playing.", checked: true, type: "string", reverse: false },
        leagueType: { label: "League Type", description: "Type of league (e.g., NCAA, Pro, G-League, NBL).", checked: false, type: "string", reverse: false }
      }
    },
    gameLogs: {
      label: "Game Logs",
      description: "List of game logs for the player.",
      checked: true,
      reverse: false,
      fields: {
        gameId: { label: "Game ID", description: "Unique identifier for the game.", checked: false, type: "number", reverse: false },
        league: { label: "League", description: "League in which the game was played.", checked: false, type: "string", reverse: false },
        date: { label: "Date", description: "Date of the game (ISO format).", checked: true, type: "string", reverse: true },
        team: { label: "Team", description: "Player's team in the game.", checked: false, type: "string", reverse: false },
        teamId: { label: "Team ID", description: "Unique identifier for the team.", checked: false, type: "number", reverse: false },
        opponentId: { label: "Opponent ID", description: "Unique identifier for the opponent team.", checked: false, type: "number", reverse: false },
        isHome: { label: "Is Home", description: "Indicates if the game was played at home (1 for true, 0 for false).", checked: false, type: "number", reverse: false },
        opponent: { label: "Opponent", description: "Name of the opponent team.", checked: false, type: "string", reverse: false },
        homeTeamPts: { label: "Home Team Points", description: "Points scored by the home team.", checked: false, type: "number", reverse: false },
        visitorTeamPts: { label: "Visitor Team Points", description: "Points scored by the visiting team.", checked: false, type: "number", reverse: false },
        gp: { label: "Games Played", description: "Games played by the player in this log.", checked: true, type: "number", reverse: false },
        gs: { label: "Games Started", description: "Games started by the player in this log.", checked: false, type: "number", reverse: false },
        timePlayed: { label: "Time Played", description: "Time played in MM:SS format.", checked: false, type: "string", reverse: false },
        fgm: { label: "Field Goals Made", description: "Field goals made.", checked: true, type: "number", reverse: false },
        fga: { label: "Field Goals Attempted", description: "Field goals attempted.", checked: false, type: "number", reverse: true },
        tpm: { label: "Three-Pointers Made", description: "Three-point field goals made.", checked: false, type: "number", reverse: false },
        tpa: { label: "Three-Pointers Attempted", description: "Three-point field goals attempted.", checked: false, type: "number", reverse: true },
        ftm: { label: "Free Throws Made", description: "Free throws made.", checked: false, type: "number", reverse: false },
        fta: { label: "Free Throws Attempted", description: "Free throws attempted.", checked: false, type: "number", reverse: true },
        oreb: { label: "Offensive Rebounds", description: "Offensive rebounds.", checked: false, type: "number", reverse: false },
        dreb: { label: "Defensive Rebounds", description: "Defensive rebounds.", checked: false, type: "number", reverse: false },
        reb: { label: "Total Rebounds", description: "Total rebounds.", checked: true, type: "number", reverse: false },
        ast: { label: "Assists", description: "Assists made.", checked: true, type: "number", reverse: false },
        stl: { label: "Steals", description: "Steals made.", checked: false, type: "number", reverse: false },
        blk: { label: "Blocks", description: "Blocks made.", checked: false, type: "number", reverse: false },
        tov: { label: "Turnovers", description: "Turnovers committed.", checked: false, type: "number", reverse: true },
        pf: { label: "Personal Fouls", description: "Personal fouls committed.", checked: false, type: "number", reverse: true },
        pts: { label: "Points", description: "Points scored.", checked: true, type: "number", reverse: false },
        plusMinus: { label: "Plus/Minus", description: "Plus/minus rating.", checked: false, type: "number", reverse: false },
        rn: { label: "Rank", description: "Rank or order in the game log.", checked: false, type: "number", reverse: true }
      }
    },
    seasonLog: {
      label: "Season Log",
      description: "Aggregated season statistics for the player.",
      checked: true,
      reverse: false,
      fields: {
        age: { label: "Age", description: "Player's age as a string.", checked: false, type: "string", reverse: true },
        League: { label: "League", description: "League in which the player participated.", checked: false, type: "string", reverse: false },
        Team: { label: "Team", description: "Team the player was part of.", checked: true, type: "string", reverse: false },
        w: { label: "Wins", description: "Number of wins for the team in the season.", checked: false, type: "number", reverse: false },
        l: { label: "Losses", description: "Number of losses for the team in the season.", checked: false, type: "number", reverse: true },
        GP: { label: "Games Played", description: "Games played by the player.", checked: true, type: "number", reverse: false },
        GS: { label: "Games Started", description: "Games started by the player.", checked: false, type: "number", reverse: false },
        MP: { label: "Minutes Played", description: "Minutes played by the player.", checked: true, type: "number", reverse: false },
        FGM: { label: "Field Goals Made", description: "Field goals made by the player.", checked: false, type: "number", reverse: false },
        FGA: { label: "Field Goals Attempted", description: "Field goals attempted by the player.", checked: false, type: "number", reverse: true },
        "FG%": { label: "Field Goal %", description: "Field goal percentage.", checked: false, type: "number", reverse: false },
        FG2M: { label: "2PT Field Goals Made", description: "Two-point field goals made.", checked: false, type: "number", reverse: false },
        FG2A: { label: "2PT Field Goals Attempted", description: "Two-point field goals attempted.", checked: false, type: "number", reverse: true },
        "FG2%": { label: "2PT Field Goal %", description: "Two-point field goal percentage.", checked: false, type: "number", reverse: false },
        "eFG%": { label: "Effective FG %", description: "Effective field goal percentage.", checked: false, type: "number", reverse: false },
        "3PM": { label: "3PT Field Goals Made", description: "Three-point field goals made.", checked: false, type: "number", reverse: false },
        "3PA": { label: "3PT Field Goals Attempted", description: "Three-point field goals attempted.", checked: false, type: "number", reverse: true },
        "3P%": { label: "3PT Field Goal %", description: "Three-point field goal percentage.", checked: false, type: "number", reverse: false },
        FT: { label: "Free Throws Made", description: "Free throws made.", checked: false, type: "number", reverse: false },
        FTA: { label: "Free Throws Attempted", description: "Free throws attempted.", checked: false, type: "number", reverse: true },
        FTP: { label: "Free Throw %", description: "Free throw percentage.", checked: false, type: "number", reverse: false },
        ORB: { label: "Offensive Rebounds", description: "Offensive rebounds.", checked: false, type: "number", reverse: false },
        DRB: { label: "Defensive Rebounds", description: "Defensive rebounds.", checked: false, type: "number", reverse: false },
        TRB: { label: "Total Rebounds", description: "Total rebounds.", checked: true, type: "number", reverse: false },
        AST: { label: "Assists", description: "Assists made by the player.", checked: true, type: "number", reverse: false },
        STL: { label: "Steals", description: "Steals made by the player.", checked: false, type: "number", reverse: false },
        BLK: { label: "Blocks", description: "Blocks made by the player.", checked: false, type: "number", reverse: false },
        TOV: { label: "Turnovers", description: "Turnovers committed by the player.", checked: false, type: "number", reverse: true },
        PF: { label: "Personal Fouls", description: "Personal fouls committed by the player.", checked: false, type: "number", reverse: true },
        PTS: { label: "Points", description: "Total points scored by the player.", checked: true, type: "number", reverse: false }
      }
    },
    scoutRanking: {
      label: "Scout Ranking",
      description: "Scouting rankings from various sources.",
      checked: false,
      reverse: false,
      fields: {
        "ESPN Rank": { label: "ESPN Rank", description: "Player's rank according to ESPN.", checked: true, type: "number", reverse: true },
        "Sam Vecenie Rank": { label: "Sam Vecenie Rank", description: "Player's rank according to Sam Vecenie.", checked: false, type: "number", reverse: true },
        "Kevin O'Connor Rank": { label: "Kevin O'Connor Rank", description: "Player's rank according to Kevin O'Connor.", checked: false, type: "number", reverse: true },
        "Kyle Boone Rank": { label: "Kyle Boone Rank", description: "Player's rank according to Kyle Boone.", checked: false, type: "number", reverse: true },
        "Gary Parrish Rank": { label: "Gary Parrish Rank", description: "Player's rank according to Gary Parrish.", checked: false, type: "number", reverse: true }
      }
    },
    measurements: {
      label: "Measurements",
      description: "Physical and athletic measurements of the player.",
      checked: false,
      reverse: false,
      fields: {
        heightNoShoes: { label: "Height (No Shoes)", description: "Height without shoes (in inches).", checked: false, type: "number", reverse: false },
        heightShoes: { label: "Height (With Shoes)", description: "Height with shoes (in inches).", checked: false, type: "number", reverse: false },
        wingspan: { label: "Wingspan", description: "Wingspan (in inches).", checked: true, type: "number", reverse: false },
        reach: { label: "Standing Reach", description: "Standing reach (in inches).", checked: false, type: "number", reverse: false },
        maxVertical: { label: "Max Vertical", description: "Maximum vertical leap (in inches).", checked: false, type: "number", reverse: false },
        noStepVertical: { label: "No-Step Vertical", description: "Vertical leap without step (in inches).", checked: false, type: "number", reverse: false },
        weight: { label: "Weight", description: "Weight (in pounds).", checked: false, type: "number", reverse: false },
        bodyFat: { label: "Body Fat %", description: "Body fat percentage.", checked: false, type: "number", reverse: true },
        handLength: { label: "Hand Length", description: "Hand length (in inches).", checked: false, type: "number", reverse: false },
        handWidth: { label: "Hand Width", description: "Hand width (in inches).", checked: false, type: "number", reverse: false },
        agility: { label: "Agility", description: "Agility test time (in seconds).", checked: false, type: "number", reverse: true },
        sprint: { label: "Sprint", description: "Sprint time (in seconds).", checked: false, type: "number", reverse: true },
        shuttleLeft: { label: "Shuttle Left", description: "Shuttle run left time (in seconds).", checked: false, type: "number", reverse: true },
        shuttleRight: { label: "Shuttle Right", description: "Shuttle run right time (in seconds).", checked: false, type: "number", reverse: true },
        shuttleBest: { label: "Shuttle Best", description: "Best shuttle run time (in seconds).", checked: false, type: "number", reverse: true }
      }
    }
  } as const;

export { FullPlayerDataFieldInfo };